### PR TITLE
Lps 53386

### PR DESCRIPTION
**Pull request by shuyangzhou**

### CODE REVIEW

**Comment by shuyangzhou** [comment]
For https://github.com/shuyangzhou/arquillian-extension-liferay/commit/1fbbd7c5f6f440ce3f5769d7cde1f0750bf12625, without it you will get a bundle of class cast exception at runtime, as junit are loaded twice by 2 different classloaders, and they are trying to cross referring each other.

For https://github.com/shuyangzhou/arquillian-extension-liferay/commit/c9be16dfa18634d5bd87796caa9e3bd49c36a1c0, what you want to wait for is Spring DM context, not OSGi context in general. For a plain OSGi bundle (who is not using Spring DM), it will be there sitting idle until timeout, this is what happening to polls-test

For https://github.com/shuyangzhou/arquillian-extension-liferay/commit/9ed534fca99f54283b4d5ebb181dcc4c30de2ef7, you can move it anywhere you like, as long as it is exported properly, so that integration tests in module can see it at both compile and runtime.

This pull works correctly against https://github.com/brianchandotcom/liferay-portal/pull/23945 , if you have better idea to do this while still maintaining the tests working, please go for it, at all this is your extension, you can do it the way you prefer, as long as it works.

Thanks

Shuyang

**Comment by cgoncas** [comment]
Hey @shuyangzhou 

What do you think if you include portal-test (using include-resource) in polls-test?, this way you don't need to install portal-test in portal, so you don't need to have the junit dependency. 

In the future will be posible to configure the bnd file, so the dependencies will be installed dinamically from a BND repo, but for now, what do you think to use this solution for installing dependencies as portal-test, portal-test-internal or spring-test?

Thanks!!

**Comment by shuyangzhou** [comment]
I guess it would work.

**Comment by cgoncas** [comment]
Just started reviewing :) <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Comment by cgoncas** [comment]
Pull request submitted to https://github.com/csierra/arquillian-extension-liferay/pull/7. <br><br>:octocat: _Sent from [GH](http://nodegh.io)._

**Pull request closed without merging**
